[package]
name = "t21l"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6"
ggrs = "0.8"
bevy_ggrs = "0.1.3"
matchbox_socket = { version = "0.3", features = ["ggrs-socket"] }
